#!/usr/bin/env python3
"""Derive the Qwen3.8 NVFP4 projection census from a produced Physical Plan command dump.

The census is *derived*, never hand-maintained: the command dump is produced by the e2e artifact
binary with ``SUPERINFER_QWEN38_DUMP_PLAN_COMMANDS`` and every `nvfp4_linear` command is validated
against the packed/scale byte counts before it is counted. The benchmark that exercises the native
MMA path includes the generated header and asserts the totals, so a stale or partial census fails the
build/run instead of silently under-measuring.

Usage (regenerate evidence + benchmark table):
    SUPERINFER_QWEN38_ARTIFACT=build/evidence/qwen38-payload-v1-final-a.sinf \
    SUPERINFER_QWEN38_DUMP_PLAN_COMMANDS=1 \
    build/cuda-sm120a/tests/superinfer_sm120_qwen38_e2e_artifact > /tmp/plan-commands.txt

    python tools/qwen38_nvfp4_census.py \
        --commands /tmp/plan-commands.txt \
        --out artifacts/S04/p8r/nvfp4-census.json \
        --emit-header tests/gpu/sm120/qwen38_nvfp4_census_generated.h
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path

# PhysicalDType enum order (include/superinfer/ir/physical_plan.hpp).
PHYSICAL_DTYPE_NAMES = {
    0: "unknown",
    1: "f32",
    2: "f16",
    3: "bf16",
    4: "int8",
    5: "int32",
    6: "u8",
}
NVFP4_LINEAR_KERNEL_ID = 13
NVFP4_LINEAR_OPERANDS = 5  # f32 input, u8 packed, u8 scales, f32 tensor scale, f32 output
_COMMAND_RE = re.compile(r"^id=(\d+) kernel=(\d+) buffers=(.*)$")


@dataclass(frozen=True)
class Nvfp4Shape:
    rows: int
    inputs: int

    @property
    def packed_bytes(self) -> int:
        return self.rows * (self.inputs // 2)


def parse_commands(text: str) -> list[tuple[int, list[tuple[int, int, int]]]]:
    """Return (kernel_id, [(buffer_id, size, dtype)]) for every well-formed command."""
    commands: list[tuple[int, list[tuple[int, int, int]]]] = []
    for line in text.splitlines():
        match = _COMMAND_RE.match(line)
        if match is None:
            continue
        kernel_id = int(match.group(2))
        buffers: list[tuple[int, int, int]] = []
        for token in match.group(3).split(","):
            buffer_id, size, dtype = (int(part) for part in token.split(":"))
            buffers.append((buffer_id, size, dtype))
        commands.append((kernel_id, buffers))
    return commands


def derive_census(text: str) -> tuple[dict[Nvfp4Shape, int], list[str]]:
    errors: list[str] = []
    counts: dict[Nvfp4Shape, int] = {}
    total = 0
    for kernel_id, buffers in parse_commands(text):
        if kernel_id != NVFP4_LINEAR_KERNEL_ID:
            continue
        total += 1
        if len(buffers) != NVFP4_LINEAR_OPERANDS:
            errors.append(f"nvfp4_linear command has {len(buffers)} operands")
            continue
        (_, input_bytes, input_dtype), (_, packed_bytes, packed_dtype), (
            _,
            scales_bytes,
            scales_dtype,
        ), (_, tensor_bytes, _), (_, output_bytes, output_dtype) = buffers
        if input_dtype != 1 or output_dtype != 1:
            errors.append("nvfp4_linear input/output must be f32")
            continue
        if packed_dtype != 6 or scales_dtype != 6:
            errors.append("nvfp4_linear packed/scales must be u8 storage")
            continue
        if input_bytes % 4 or output_bytes % 4:
            errors.append("nvfp4_linear f32 operand byte count is not a multiple of 4")
            continue
        inputs = input_bytes // 4
        rows = output_bytes // 4
        if inputs % 16:
            errors.append(f"nvfp4_linear K={inputs} is not a multiple of 16")
            continue
        if packed_bytes != rows * (inputs // 2):
            errors.append(f"packed bytes {packed_bytes} != rows*K/2 for {rows}x{inputs}")
            continue
        if scales_bytes != rows * (inputs // 16):
            errors.append(f"scale bytes {scales_bytes} != rows*K/16 for {rows}x{inputs}")
            continue
        if tensor_bytes != 4:
            errors.append("nvfp4_linear tensor scale is not one f32")
            continue
        shape = Nvfp4Shape(rows=rows, inputs=inputs)
        counts[shape] = counts.get(shape, 0) + 1
    if total == 0:
        errors.append("no nvfp4_linear commands found in the dump")
    return counts, errors


def render_header(counts: dict[Nvfp4Shape, int], *, provenance: str) -> str:
    ordered = sorted(counts.items(), key=lambda item: (-item[1], -item[0].rows, -item[0].inputs))
    total = sum(counts.values())
    lines = [
        "// Generated by tools/qwen38_nvfp4_census.py --emit-header. Do not edit by hand.",
        f"// Provenance: {provenance}",
        "#pragma once",
        "",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace superinfer::sm120::qwen38_census {",
        "",
        "struct ProjectionClass final {",
        "  const char* name;",
        "  std::uint64_t rows;",
        "  std::uint64_t inputs;",
        "  std::uint64_t count;",
        "};",
        "",
        f"inline constexpr std::size_t kTotalNvfp4Launches = {total};",
        "",
        f"inline constexpr std::array<ProjectionClass, {len(ordered)}> kProjectionClasses{{{{",
    ]
    for shape, count in ordered:
        lines.append(
            f'    {{"{shape.rows}x{shape.inputs}", {shape.rows}U, {shape.inputs}U, {count}U}},'
        )
    lines += ["}};", "", "}  // namespace superinfer::sm120::qwen38_census", ""]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--commands", type=Path, required=True, help="Physical Plan command dump")
    parser.add_argument("--out", type=Path, help="write the census JSON here")
    parser.add_argument("--emit-header", type=Path, help="write the generated C++ census header here")
    parser.add_argument("--expect-total", type=int, default=401, help="asserted nvfp4_linear count")
    parser.add_argument("--provenance", default="", help="artifact/binary provenance string")
    args = parser.parse_args()

    text = args.commands.read_text()
    counts, errors = derive_census(text)
    for error in errors:
        print(f"census error: {error}", file=sys.stderr)
    total = sum(counts.values())
    if total != args.expect_total:
        print(f"census total {total} != expected {args.expect_total}", file=sys.stderr)
        return 2
    if errors:
        return 2

    ordered = sorted(counts.items(), key=lambda item: (-item[1], -item[0].rows, -item[0].inputs))
    payload = {
        "kernel_id": NVFP4_LINEAR_KERNEL_ID,
        "kernel_name": "nvfp4_linear",
        "total_launches_per_token": total,
        "command_dump_sha256": hashlib.sha256(text.encode()).hexdigest(),
        "provenance": args.provenance,
        "classes": [
            {
                "name": f"{shape.rows}x{shape.inputs}",
                "rows": shape.rows,
                "inputs": shape.inputs,
                "count": count,
                "packed_bytes_per_launch": shape.packed_bytes,
                "packed_mb_per_token": shape.packed_bytes * count / 1e6,
            }
            for shape, count in ordered
        ],
    }
    print(json.dumps(payload, indent=2, sort_keys=True))
    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    if args.emit_header is not None:
        args.emit_header.write_text(render_header(counts, provenance=args.provenance))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
